spring:
  datasource:
    url: jdbc:mysql://localhost/school
    username: schoolservice
    password: '{cipher}54a83d553a8567642079772f77c6f874316917635dafeca01063d650c002384c'
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
        ddl-auto: none
        naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.hbm2ddl.auto: validate    

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
