spring:
  datasource:
    url: jdbc:mysql://localhost/school
    username: schoolservice
    password: '{cipher}0834772989b3953c1a2bd3fc2ba6211239ca6877cffc3f6afb63dacdcfec96bb'
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
        ddl-auto: none
        naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
        hibernate.hbm2ddl.auto: validate    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
